# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 543)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 270, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Sign = QtWidgets.QPushButton(self.centralwidget)
        self.Sign.setGeometry(QtCore.QRect(280, 450, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sign.setFont(font)
        self.Sign.setObjectName("Sign")
        self.txt_sign = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(140, 270, 681, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_sign.setFont(font)
        self.txt_sign.setObjectName("txt_sign")
        self.Verify = QtWidgets.QPushButton(self.centralwidget)
        self.Verify.setGeometry(QtCore.QRect(570, 450, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Verify.setFont(font)
        self.Verify.setObjectName("Verify")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 90, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 20, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_info = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(140, 90, 681, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_info.setFont(font)
        self.txt_info.setObjectName("txt_info")
        self.Generate_keys = QtWidgets.QPushButton(self.centralwidget)
        self.Generate_keys.setGeometry(QtCore.QRect(530, 30, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Generate_keys.setFont(font)
        self.Generate_keys.setObjectName("Generate_keys")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Signature:"))
        self.Sign.setText(_translate("MainWindow", "Sign"))
        self.Verify.setText(_translate("MainWindow", "Verify"))
        self.label.setText(_translate("MainWindow", "Information:"))
        self.label_2.setText(_translate("MainWindow", "ECC CIPHER"))
        self.Generate_keys.setText(_translate("MainWindow", "Generate_keys"))
